---
- name: Config My ELK VM with Docker
  hosts: elk
  become: true
  tasks:
    - name: Install docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    - name: Install python-pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Docker Python module
      pip:
        name: docker
        state: present

    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

    - name: Increase virtual memory on restart
      sysctl: 
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes

    - name: Download and launch a Docker ELK container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
